version: 2
jobs:
  build:
    working_directory: ~/workspace/circleCi-demo
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
  test:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
  deployment:
        steps:
           - run: bash .circleci/setup-heroku.sh
           - add_ssh_keys:
               fingerprints:
                 - "48:a0:87:54:ca:75:32:12:c6:9e:a2:77:a4:7a:08:a4"
           - deploy:
               name: Deploy Master to Heroku
               command: |
                 if [ "${CIRCLE_BRANCH}" == "master" ]; then
                   git push heroku master
                   heroku run python manage.py deploy
                   heroku restart
                 fi